# -*- coding: utf-8 -*-
"""evenOddList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10QYKGFCrScudwU_0SshLiZAFcijGRsmf

**program to filter the list element in even then odd manner using the same**
"""

import random
l1 = [random.randint(1, 10) for i in range(1, 10)]

l1

i, j = 0, len(l1) - 1

while i < j:
  if l1[i] % 2 == 0:
    i += 1
  l1[i], l1[j] = l1[j], l1[i]
  if l1[j] % 2 != 0:
    j = j - 1

l1