# -*- coding: utf-8 -*-
"""day-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GGK8kq5RppbI2wO1zWU-pH188GsdR4W
"""

#string
name = "Tarun Kumar"
print(name)

# reverse a string
name[::-1]

# multiline strings
str1 = '''Hello
world
This is a python
multiline string example'''
str1

# Formatted Strings
name = 'Tarun'
formattedString = f'Hello, {name}'
formattedString

# string method
# upper case
str2 = 'hello, welcome to python class in kiit university'
str2.upper()

# lower case
str3 = "WELCOME TO THE GREAT KIIT UNIVERSITY"
str3.lower()

# slicing
trimString = str3[:8]
trimString

# returning index position
str3.index('G')

# generating random number
import random
num = []
for i in range(10):
    num.append(random.randint(1, 100))
num

import random
num2 = []
for i in range(5):
    num2.append(random.randint(1, 100))
num2

#extend method
num2.extend(num)
print(num2)

# list comprehension
ran1 = [random.randint(1, 100) for _ in range(20)]
print(ran1)

# reverse a list
def reverseList(lst):
  lst1 = lst[::-1]
  return lst1

#calling function
print("Original list: ", num)
revlst = reverseList(num)
print("Reverse list: ", revlst)

# Bubble sort
def bubbleSort(lst):
    n = len(lst)
    for i in range(n):
        for j in range(0, n-i-1):
            if lst[j] > lst[j+1]:
                lst[j], lst[j+1] = lst[j+1], lst[j]

random_numbers = [random.randint(1, 100) for _ in range(10)]

print("Original list:", random_numbers)
bubbleSort(random_numbers)

print("Sorted list:", random_numbers)

# selection sort
import random
def selectionSort(num, n):
    for i in range(0, n-1):
        min = i
        swap = 0
        for j in range(i+1, n):
            if num[j] < num[min]:
                min = j
                swap = 1
        if min != i:
            num[i],num[min] = num[min],num[i]
        if swap == 0:
            break
number = [random.randint(1, 100) for _ in range(10)]
length = len(number)
print("Original list: ", number)
selectionSort(number, length)
print("Sorted list: ", number)

# insertion sort
import random
def insertion_sort(arr):
    n = len(arr)

    for j in range(1, n):
        key = arr[j]
        i = j - 1

        while i >= 0 and arr[i] > key:
            arr[i + 1] = arr[i]
            i -= 1

        arr[i + 1] = key

random_numbers = [random.randint(1, 100) for _ in range(10)]

print("Original list:", random_numbers)
insertion_sort(random_numbers)

print("Sorted list:", random_numbers)