# -*- coding: utf-8 -*-
"""gusseGame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVG45sWKEuNfzyC67B-TDyyPJQP-zfm9
"""

import random
lower, upper = int(input("Enter lower limit: ")), int(input("Enter upper limit: "))
num = random.randint(lower, upper)

while 1:
  guess = int(input("Enter your guess: "))
  if guess > lower and guess < num:
    print("Guess is too low")
    continue
  elif guess < upper and guess > num:
    print("Guess is too high")
    continue
  elif guess == num :
    print("Your guess is correct")
    break

